### ISSUE TITLE
README mentions package but not where to find it

### ISSUE THREAD

**Issue by nick-prater** [BytemarkHosting/byteback#2]
README.md says:
> Install the 'byteback' package on the server, along with its dependencies.

But makes no mention of where to obtain this package or how to build it or what dependencies are required. I have searched internet and specifically Bytemark forums and failed to find a built package.

(I'm in the process of trying to get byteback running on a Bytemark Symbiosis machine which is Debian based. This looks a great solution, if I can get it working.)

**Comment by skx** [comment]
I'll try to get this fixed tomorrow.  In the mean-time we've got packages for Debian and some versions of Ubuntu, beneath this location:

* http://repo.bytemark.co.uk/byteback/

So, for example, you should be able to create `/etc/apt/sources.list.d/byteback.list` with contents like:

      deb http://repo.bytemark.co.uk/byteback/jessie ./

(That's assuming you're running the `jessie` release of Symbiosis.)

Repositories are somewhat in flux at the moment, as you can see via the contents of that directory.  But we'll aim to ensure that things don't break with symlinks.

**Comment by nick-prater** [comment]
Thank you! I now have it up and running and like it very much. It took me a while, but then I'm not familiar with lvm, btrfs or ruby and am running ssh on a non-standard port, so it's been a day of learning! Appreciate the software and your response.

**Comment by skx** [comment]
This should now be resolved, [via this commit](https://github.com/BytemarkHosting/byteback/commit/1091a3252042cb6fa9406c231a083707214a4170).
